spring.application.name=backend

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/tech_store
spring.datasource.username=root
spring.datasource.password=Aabcd_03

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

#configurations
#JWT
myapp.jwtSecret=9f3b7d8c1a2e4f6g8h0j9k2l3m5n7p1q
myapp.jwtExpirationMs=86400000

#email configurations

#oauth2 configurations