spring.application.name=backend

# Database configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/tech_store
# spring.datasource.username=root
# spring.datasource.password=Aabcd_03


# Kết nối tới Database
spring.datasource.url=jdbc:mysql://localhost:3306/tech_store
spring.datasource.username=thoaipq
spring.datasource.password=Aabcd_03
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình Hibernate (JPA)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#configurations
#JWT
myapp.jwtSecret=9f3b7d8c1a2e4f6g8h0j9k2l3m5n7p1q
# # Expiration time in milliseconds (15 minutes)
# 1000 * 60 * 15 
# myapp.jwtAccessTokenExpiration= 900000
myapp.jwtAccessTokenExpiration=60000

# # Expiration time in milliseconds (7 daysa)
# 1000 * 60 * 60 * 24 * 7
# myapp.jwtRefreshTokenExpiration=604800000
# Expiration time in milliseconds (5m for testing)
myapp.jwtRefreshTokenExpiration=300000
#httponly cookie
myapp.cookie.secure = false

#email configurations

#nctp hibs wsey bqse
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username = thoaillbebackenddev@gmail.com
spring.mail.password = nctp hibs wsey bqse

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#oauth2 configurations